マークダウンファイルの先頭にYAMLを埋め込む
takeyuwebinc/scrapbox2markdown pull request #5
Opened 2018-07-05 11:31 UTC by noriyotcp

Closes #4 

JSONから`title`, `created`, `updated` の値を取り出し、以下の形式にしてマークダウンに埋め込む

```yaml
---
title: "はじめに"
created_at: 2018-03-26 22:52:30 +0900
updated_at: 2018-04-21 11:51:09 +0900
---

（ここから本文）
```

インポートする際に例えば以下のようにする

https://help.docbase.io/posts/46870?list=%2Fsearch&q=%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88

```rb
    post_json = {
      title:  "#{data['title']}",
      (snip)
      published_at: data['created_at'].iso8601,
    }.to_json
```

2018-07-05 15:13 UTC, takeyuweb requested changes

2018-07-05 15:13 UTC, takeyuweb commented on lib/scrapbox2markdown/file_generator.rb
> +        header = yaml_header(page)
この変数いらないですね

2018-07-05 15:13 UTC, takeyuweb commented on lib/scrapbox2markdown/file_generator.rb
> +      title: "#{page['title']}"
Titleにセミコロンを含むケースはないですか？
YAMLライブラリを使った方が安全じゃないかと思います。（CSVもそうですが、文字列でがんばると漏れでフォーマット壊れたりするので、ライブラリを使った方が良いです）

2018-07-06 03:58 UTC, noriyotcp commented on lib/scrapbox2markdown/file_generator.rb
> +      title: "#{page['title']}"
ちょっとうまくいっていないです

区切り線を２つ入れたいので`dump_stream` を使用したり

https://magazine.rubyist.net/articles/0010/0010-YAML.html

空行入れたいので`nil` にしてみたり

https://rubyist.g.hatena.ne.jp/lnznt/20120403/1333379074

その他もろもろ出力結果が期待しているのと違っています

```rb
    def yaml_header(page)
      title = 'hajimeni; test' # テスト用にセミコロンの入ったタイトルを用意する
      hash_list = [
        { "title" => "#{title}", "created_at" => Time.at(page['created']), "updated_at" => Time.at(page['updated']) },
        nil
      ]
      YAML.dump_stream(*hash_list)
    end
```

```
---
title: hajimeni; test # ダブルクォーツで囲われてない
created_at: 2018-03-26 22:52:30.000000000 +09:00 # なんか思ってたのと違う
updated_at: 2018-04-21 11:51:09.000000000 +09:00
--- 
... # 空行を入れたいのだが・・・
（ここから本文）
```

2018-07-06 04:20 UTC, noriyotcp commented on lib/scrapbox2markdown/file_generator.rb
> +      title: "#{page['title']}"
インポートスクリプトを試しに書いてみました

```ruby
require 'yaml'

EXPORTED_DIR_PATH = './spec/exports/generated'

Dir.glob "#{EXPORTED_DIR_PATH}/**/*.md" do |path|
  open path do |file|
    text = file.read

    data = YAML.load(text)
    body = text.sub(/\A---$.*?^---$/m, '')
    binding.irb
  end
end
```

```sh
> data
=> {"title"=>"hajimeni; test", "created_at"=>2018-03-26 22:52:30 +0900, "updated_at"=>2018-04-21 11:51:09 +0900}
> data['title']
=> "hajimeni; test"
> require 'time'
=> true
> data['created_at'].iso8601
=> "2018-03-26T22:52:30+09:00"

# yamlを取り除けてないので正規表現の修正が必要そう
> body
=> "---\ntitle: hajimeni; test\ncreated_at: 2018-03-26 22:52:30.000000000 +09:00\nupdated_at: 2018-04-21 11:51:09.000000000 +09:00\n--- \n...\nはじめに\nこのプロジェクトはscrapboxからdocbaseへとエクスポートするものです。\n\n
...
```

2018-07-06 04:35 UTC, takeyuweb commented on lib/scrapbox2markdown/file_generator.rb
> +      title: "#{page['title']}"
あ、すみませんセミコロンじゃない言いたかったのはダブルクォーテーションでした
『"こういうの"』です。

クォートの件はこれですね
http://itiskj.hatenablog.com/entry/2017/08/09/%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89%E3%81%8C%E5%BF%85%E8%A6%81%E3%81%AA%E6%96%87%E5%AD%97%E3%81%AE%E6%99%82YAML.dump%E3%81%AFvalue%E3%82%92%E3%82%AF%E3%82%AA%E3%83%BC%E3%83%88%E3%81%A7%E3%83%A9

この場合大事なのは「思ってたのと違う」ではなく、シリアライズしたものをデシリアライズしたときに期待した結果が得られることなので、それをテストする方針で良いと思いますよ。

2018-07-06 05:02 UTC, noriyotcp commented
@takeyuweb 修正しました

このように出力されています

```md
---
title: はじめに
created_at: 2018-03-26 22:52:30.000000000 +09:00
updated_at: 2018-04-21 11:51:09.000000000 +09:00
---

はじめに
このプロジェクトはscrapboxからdocbaseへとエクスポートするものです。
```

先ほどのインポート例では正規表現は修正しなくてよくなりましたが、頭の改行取り除けてないようです

```sh
> body
"\n\nはじめに\nこのプロジェクトはscrapboxからdocbaseへとエクスポートするものです。
```

2018-07-06 18:10 UTC, takeyuweb commented
@noriyotcp インポート時の先頭の改行コードはインポートスクリプトの調整でよいかと。

2018-07-06 18:17 UTC, takeyuweb requested changes
出力したファイルのYAMLメタ情報を復元してみて値を確認するspec欲しいです

あと、レビュー流しましたけど、 `test.json` は `spec` ディレクトリの下に置くべきぽい

spec中でファイルを書き出したりするところは、こないだ人と話してたのですが `tempdir` を使うなどして一時ディレクトリを作るか `/tmp` に書き出すようにするという対応が一般的みたいです。

https://magazine.rubyist.net/articles/0029/0029-BundledLibraries.html

2018-07-09 02:48 UTC, noriyotcp commented on spec/scrapbox2markdown/file_generator_spec.rb
> +                       "created_at" => Time.new(2018, 03, 26, 22, 52, 30, '+09:00'),
markdownに出力された時は`2018-03-26 22:52:30.000000000 +09:00` この形であるが、`YAML.load` した際のハッシュの値は `2018-03-26 22:52:30 +09:00` こうなっていた

引数として渡す際にTimeオブジェクトそのままではシンタックスエラーになったので、`Time.new` しています

2018-07-10 01:59 UTC, takeyuweb approved these changes

2018-07-10 01:59 UTC, merged